---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
    run_list: apt

suites:
  - name: install
    run_list:
      - openshift-test::default
      - openshift::install
    attributes:
